<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Title>CommandParsonaut</Title>
    <Description>Simple C# terminal &amp; commands parser tool.</Description>
    <RepositoryUrl>https://github.com/kerrambit/CommandParsonaut</RepositoryUrl>
    <Authors>kerrambit</Authors>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <Version>2.0.0</Version>
    <PackageReleaseNotes>Overview:

    FEATURE: terminal history
    FEATURE: internal major changes, easier implementation of commands for users

</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
